# Scraping Reddit using Python

Following [this](https://www.storybench.org/how-to-scrape-reddit-with-python/) tutorial. But with the `COVID19_support` subreddit.

In [1]:
#! usr/bin/env python3
# -*- coding: utf-8 -*-
import praw
import pandas as pd
import datetime as dt

Reddit app info:

In [2]:
personal_use = "NKl_46k-B3Jh6g"
secret = "XvKVjLMLm2xGXflfADlsG5WNFO8"
name = "test"
my_username = "lennyismaking"
my_password="arcobaleno00"
my_refresh="655947427667-DYJh6FB3sG1Z0UZ1tfJEC4Sbs1o"

## Getting Reddit and subreddit instances

In [3]:
reddit = praw.Reddit(client_id=personal_use, \
                     client_secret=secret, \
                     refresh_token=my_refresh, \
                     user_agent=name, \
                     username=my_username, \
                     password=my_password)

In [4]:
subreddit = reddit.subreddit("COVID19_support")

In [5]:
top_subreddit = subreddit.top(limit=10000)

In [6]:
for submission in subreddit.top(limit=1):
    print(submission.title, submission.id)

Good things to remember when you're frightened about the virus fj8s6n

## Download and save to a dictionary

In [7]:
topics_dict = { "title":[], \
                "score":[], \
                "upvote_ratio":[], \
                "id":[], \
                "url":[], \
                "comms_num": [], \
                "created": [], \
                "body":[]}

In [8]:
for submission in top_subreddit:
    topics_dict["title"].append(submission.title)
    topics_dict["score"].append(submission.score)
    topics_dict["upvote_ratio"].append(submission.upvote_ratio)
    topics_dict["id"].append(submission.id)
    topics_dict["url"].append(submission.url)
    topics_dict["comms_num"].append(submission.num_comments)
    topics_dict["created"].append(submission.created)
    topics_dict["body"].append(submission.selftext)

In [9]:
topics_data = pd.DataFrame(topics_dict)
topics_data.head()

,title,score,upvote_ratio,id,url,comms_num,created,body
0,Good things to remember when you're frightened...,1109,0.99,fj8s6n,https://www.reddit.com/r/COVID19_support/comme...,163,1.584336e+09,Here are some things I find to help me stay re...
1,My Dad (60 years old) was on the ventilator fo...,781,1.00,fyn5v4,https://www.reddit.com/r/COVID19_support/comme...,54,1.586577e+09,Hello all! if you were following my submission...
2,My dad (54) got off the ventilator yesterday a...,667,0.99,g19b73,https://www.reddit.com/r/COVID19_support/comme...,62,1.586912e+09,I write this message with great happiness and ...
3,We lost my brother this morning due to Covid-19,653,1.00,fzlpyn,https://www.reddit.com/r/COVID19_support/comme...,120,1.586677e+09,Hello to all going through this same trauma. I...
4,I’m having opposite fears than many of you...,599,0.97,gj4w34,https://www.reddit.com/r/COVID19_support/comme...,97,1.589424e+09,Whenever I see a post on this sub it’s usually...

In [10]:
topics_data.shape

(1000, 8)

## Fixing the date Column

In [11]:
def get_date(created):
    return dt.datetime.fromtimestamp(created)

In [12]:
_timestamp = topics_data["created"].apply(get_date)

In [13]:
topics_data = topics_data.assign(timestamp = _timestamp)

In [14]:
topics_data.head(10)

,title,score,upvote_ratio,id,url,comms_num,created,body,timestamp
0,Good things to remember when you're frightened...,1109,0.99,fj8s6n,https://www.reddit.com/r/COVID19_support/comme...,163,1.584336e+09,Here are some things I find to help me stay re...,2020-03-16 01:19:04
1,My Dad (60 years old) was on the ventilator fo...,781,1.00,fyn5v4,https://www.reddit.com/r/COVID19_support/comme...,54,1.586577e+09,Hello all! if you were following my submission...,2020-04-10 23:45:02
2,My dad (54) got off the ventilator yesterday a...,667,0.99,g19b73,https://www.reddit.com/r/COVID19_support/comme...,62,1.586912e+09,I write this message with great happiness and ...,2020-04-14 21:00:43
3,We lost my brother this morning due to Covid-19,653,1.00,fzlpyn,https://www.reddit.com/r/COVID19_support/comme...,120,1.586677e+09,Hello to all going through this same trauma. I...,2020-04-12 03:42:25
4,I’m having opposite fears than many of you...,599,0.97,gj4w34,https://www.reddit.com/r/COVID19_support/comme...,97,1.589424e+09,Whenever I see a post on this sub it’s usually...,2020-05-13 22:41:18
5,Hubby is off the vent after 13 days (21 days t...,594,0.99,g3t9r7,https://www.reddit.com/r/COVID19_support/comme...,74,1.587266e+09,He called me this morning and said he feels li...,2020-04-18 23:20:44
6,"My Mom, an RN, passed away Saturday from COVID...",589,0.99,g1t6dq,https://www.reddit.com/r/COVID19_support/comme...,55,1.586990e+09,She was an amazing woman. My heart is complet...,2020-04-15 18:40:07
7,Just some things to remember to keep yourself ...,582,0.99,fit4z8,https://www.reddit.com/r/COVID19_support/comme...,70,1.584263e+09,It’s been hard to come to terms with this viru...,2020-03-15 05:04:48
8,"NYC ER doctor recovers from COVID, back to wor...",550,1.00,fx8u9n,https://nyti.ms/2XeoHy5,42,1.586390e+09,,2020-04-08 19:47:57
9,My mother is in the icu on life support and te...,511,1.00,fqc00k,https://www.reddit.com/r/COVID19_support/comme...,70,1.585393e+09,We’re in Southern California.This doesn’t feel...,2020-03-28 06:58:56

In [15]:
topics_data.tail(10)

,title,score,upvote_ratio,id,url,comms_num,created,body,timestamp
990,Moving and grieving in these crazy times. How ...,23,1.00,i9h7fw,https://www.reddit.com/r/COVID19_support/comme...,2,1.597417e+09,"Okay first time poster, short time lurker. \n\...",2020-08-14 10:54:37
991,"Losing friends, being ignored",20,0.87,i9bk5g,https://www.reddit.com/r/COVID19_support/comme...,8,1.597393e+09,I feel like no one understands the emotional p...,2020-08-14 04:12:36
992,Positivity Fatigue,22,0.97,i4bdpd,https://www.reddit.com/r/COVID19_support/comme...,4,1.596683e+09,"No one likes a complainer, I know. I wrote th...",2020-08-05 22:57:24
993,Annoyed with my family,23,0.93,i2jm72,https://www.reddit.com/r/COVID19_support/comme...,6,1.596431e+09,I have been getting annoyed with my family rec...,2020-08-03 00:58:38
994,Is it true that most people suffer terrible lo...,21,1.00,i1zc0i,https://www.reddit.com/r/COVID19_support/comme...,10,1.596343e+09,I work in a higher risk job and I am going bac...,2020-08-02 00:38:06
995,I need a reason to feel hopeful right now,21,1.00,hyj065,https://www.reddit.com/r/COVID19_support/comme...,13,1.595842e+09,Dr. Fauci recently stated that a vaccine proba...,2020-07-27 05:28:11
996,Any fellow pre-existing condition peeps out th...,19,0.89,hxis0j,https://www.reddit.com/r/COVID19_support/comme...,9,1.595691e+09,"I'm supposedly not in the ""high risk"" category...",2020-07-25 11:28:53
997,I want to hug my mom,23,1.00,hsplpo,https://www.reddit.com/r/COVID19_support/comme...,9,1.594990e+09,I (21f) have been living away from my parents ...,2020-07-17 08:53:45
998,"Had COVID at home months ago, been lowkey trau...",23,0.97,hphgjz,https://www.reddit.com/r/COVID19_support/comme...,6,1.594529e+09,Hi! My family had COVID during the beginning o...,2020-07-12 00:49:30
999,Conan O' Brien staff writer lost her mother to...,22,1.00,ho2slg,https://www.reddit.com/r/COVID19_support/comme...,0,1.594329e+09,I never thought I could laugh at Covid but som...,2020-07-09 17:09:51

### Try to get with New

In [16]:
new_subreddit = subreddit.new(limit=100000)

In [17]:
for submission in subreddit.new(limit=1):
    print(submission.title, submission.id)

I’m just curious as to what will happen to jobs in the winter if covid will be the worst it’s ever been? Anyone care to answer? j7iewu

In [18]:
topics_dict2 = { "title":[], \
                "score":[], \
                "upvote_ratio":[], \
                "id":[], \
                "url":[], \
                "comms_num": [], \
                "created": [], \
                "body":[]}

for submission in new_subreddit:
    topics_dict2["title"].append(submission.title)
    topics_dict2["score"].append(submission.score)
    topics_dict2["upvote_ratio"].append(submission.upvote_ratio)
    topics_dict2["id"].append(submission.id)
    topics_dict2["url"].append(submission.url)
    topics_dict2["comms_num"].append(submission.num_comments)
    topics_dict2["created"].append(submission.created)
    topics_dict2["body"].append(submission.selftext)

In [19]:
topics_data2 = pd.DataFrame(topics_dict2)
topics_data2.head()

,title,score,upvote_ratio,id,url,comms_num,created,body
0,I’m just curious as to what will happen to job...,1,1.00,j7iewu,https://www.reddit.com/r/COVID19_support/comme...,1,1.602210e+09,I’ve been laid off since June due to covid and...
1,Why would we need to wear masks even with a va...,0,0.50,j7hpbl,https://www.reddit.com/r/COVID19_support/comme...,4,1.602208e+09,It doesn't make any sense to me. I've just uns...
2,"My(17f) mom(45f) has severe covid, i dont know...",6,0.88,j7dzoi,https://www.reddit.com/r/COVID19_support/comme...,5,1.602196e+09,"Not sure if this is the right sub, please redi..."
3,No idea what to believe anymore,32,0.90,j7ddv1,https://www.reddit.com/r/COVID19_support/comme...,16,1.602194e+09,"I live in the UK. It's a shit show here, the g..."
4,Fear of the swab,2,1.00,j7a42c,https://www.reddit.com/r/COVID19_support/comme...,4,1.602179e+09,"Hi there,\n\nI have intense fear of anything c..."

In [20]:
topics_data2.shape

(999, 8)

### Get with Hot

In [21]:
hot_subreddit = subreddit.hot(limit=100000)

In [22]:
for submission in subreddit.hot(limit=1):
    print(submission.title, submission.id)

NAVIGATING COVID SUPPORT i4jmw0

In [23]:
topics_dict3 = { "title":[], \
                "score":[], \
                "upvote_ratio":[], \
                "id":[], \
                "url":[], \
                "comms_num": [], \
                "created": [], \
                "body":[]}

for submission in hot_subreddit:
    topics_dict3["title"].append(submission.title)
    topics_dict3["score"].append(submission.score)
    topics_dict3["upvote_ratio"].append(submission.upvote_ratio)
    topics_dict3["id"].append(submission.id)
    topics_dict3["url"].append(submission.url)
    topics_dict3["comms_num"].append(submission.num_comments)
    topics_dict3["created"].append(submission.created)
    topics_dict3["body"].append(submission.selftext)

In [24]:
topics_data3 = pd.DataFrame(topics_dict3)

topics_data3.head()

,title,score,upvote_ratio,id,url,comms_num,created,body
0,NAVIGATING COVID SUPPORT,22,0.85,i4jmw0,https://www.reddit.com/r/COVID19_support/comme...,42,1.596711e+09,"First of all, we're glad you're here at this d..."
1,No idea what to believe anymore,29,0.86,j7ddv1,https://www.reddit.com/r/COVID19_support/comme...,16,1.602194e+09,"I live in the UK. It's a shit show here, the g..."
2,"I am COVID-19 positive, and my in-laws refuse ...",85,0.97,j74ins,https://www.reddit.com/r/COVID19_support/comme...,7,1.602152e+09,I am stuck in self isolation at my in-laws hou...
3,"My(17f) mom(45f) has severe covid, i dont know...",6,0.76,j7dzoi,https://www.reddit.com/r/COVID19_support/comme...,5,1.602196e+09,"Not sure if this is the right sub, please redi..."
4,"My friend's wedding is in less than two weeks,...",38,0.98,j725mg,https://www.reddit.com/r/COVID19_support/comme...,14,1.602143e+09,My friend and I have very different views on t...

In [25]:
topics_data3.shape

(993, 8)

## Do it all at once

1. Get each of the 5 types of post organizations: hot, new, gilded, top, controversial.
1. Add posts from each to our main_dict
1. Turn it into a Pandas object and set size

In [26]:
organizations = [subreddit.hot(limit=10000), \
                 subreddit.new(limit=10000), \
                 subreddit.top(limit=10000),\
                 subreddit.gilded(limit=10000),\
                 subreddit.controversial(limit=10000)]

In [39]:
main_dict = {"title":[], \
                "score":[], \
                "upvote_ratio":[], \
                "id":[], \
                "url":[], \
                "comms_num": [], \
                "created": [], \
                "body":[], \
                "is_sticky":[]}

In [40]:
for submission in subreddit.hot(limit=100000):
    main_dict["is_sticky"].append(str(submission.stickied))
    main_dict["title"].append(submission.title)
    main_dict["score"].append(submission.score)
    main_dict["upvote_ratio"].append(submission.upvote_ratio)
    main_dict["id"].append(submission.id)
    main_dict["url"].append(submission.url)
    main_dict["comms_num"].append(submission.num_comments)
    main_dict["created"].append(submission.created)
    main_dict["body"].append(submission.selftext)

In [41]:
for submission in subreddit.new(limit=100000):
    main_dict["is_sticky"].append(str(submission.stickied))
    main_dict["title"].append(submission.title)
    main_dict["score"].append(submission.score)
    main_dict["upvote_ratio"].append(submission.upvote_ratio)
    main_dict["id"].append(submission.id)
    main_dict["url"].append(submission.url)
    main_dict["comms_num"].append(submission.num_comments)
    main_dict["created"].append(submission.created)
    main_dict["body"].append(submission.selftext)

In [42]:
for submission in subreddit.top(limit=100000):
    main_dict["is_sticky"].append(str(submission.stickied))
    main_dict["title"].append(submission.title)
    main_dict["score"].append(submission.score)
    main_dict["upvote_ratio"].append(submission.upvote_ratio)
    main_dict["id"].append(submission.id)
    main_dict["url"].append(submission.url)
    main_dict["comms_num"].append(submission.num_comments)
    main_dict["created"].append(submission.created)
    main_dict["body"].append(submission.selftext)

In [43]:
for submission in subreddit.controversial(limit=100000):
    main_dict["is_sticky"].append(str(submission.stickied))
    main_dict["title"].append(submission.title)
    main_dict["score"].append(submission.score)
    main_dict["upvote_ratio"].append(submission.upvote_ratio)
    main_dict["id"].append(submission.id)
    main_dict["url"].append(submission.url)
    main_dict["comms_num"].append(submission.num_comments)
    main_dict["created"].append(submission.created)
    main_dict["body"].append(submission.selftext)

In [46]:
main_data = pd.DataFrame(main_dict)
main_data.shape

(3993, 9)

In [47]:
_timestamp = main_data["created"].apply(get_date)
main_data = main_data.assign(timestamp = _timestamp)

In [48]:
main_data.to_csv('raw_scrape.csv', index=False)